The first movie is called {title1} and has the following plot:
              {plot1}
              The second movie is called {title2} and has the following plot:
              {plot2}
              Give me the new title and the new plot of a movie that is a crossover of these two films.
              The title should be catchy and humorous.
              Give the result as a json string where the plot is stored in plot and title is stored in title.